import test from 'node:test';import assert from 'node:assert/strict';import{upstream,getData,readBounded,validateRows}from'../lib/proxy.mjs';import{normalize,quietNow,exposure,newTrades,escape,advanceActivity}from'../public/core.js';
const wallet='0x'+'a'.repeat(40);
test('proxy cannot target arbitrary hosts or paths',()=>{assert.throws(()=>upstream(new URLSearchParams({kind:'https://evil.com'})));assert.throws(()=>upstream(new URLSearchParams({kind:'positions',user:'../etc'})));assert.throws(()=>upstream(new URLSearchParams({kind:'leaderboard',category:'evil'})));assert.throws(()=>upstream(new URLSearchParams({kind:'activity',user:wallet,url:'https://evil.com'}))),assert.equal(new URL(upstream(new URLSearchParams({kind:'activity',user:wallet}))).hostname,'data-api.polymarket.com')});
test('bounded requests with explicit sorting',()=>{const u=new URL(upstream(new URLSearchParams({kind:'positions',user:wallet})));assert.equal(u.searchParams.get('limit'),'100');assert.equal(u.searchParams.get('sortBy'),'CURRENT')});
test('proxy rejects upstream failure and unexpected shape',async()=>{await assert.rejects(()=>getData(new URLSearchParams({kind:'closed',user:wallet}),async()=>({ok:false,status:429})),/429/);await assert.rejects(()=>getData(new URLSearchParams({kind:'closed',user:wallet}),async()=>new Response('{}')),/format changed/)});
test('night quiet hours wrap across midnight',()=>{assert.equal(quietNow('22:00','08:00',new Date(2026,0,1,23)),true);assert.equal(quietNow('22:00','08:00',new Date(2026,0,1,7)),true);assert.equal(quietNow('22:00','08:00',new Date(2026,0,1,12)),false);assert.equal(quietNow('08:00','08:00',new Date()),false)});
test('imports validate wallet and normalize preferences',()=>{assert.throws(()=>normalize({version:2}));assert.throws(()=>normalize({version:1,wallets:[{address:'javascript:x',name:'x'}]}));const s=normalize({version:1,wallets:[{address:wallet,name:'A'}],alerts:{min:-10,start:'99:99'}});assert.equal(s.alerts.min,0);assert.equal(s.alerts.start,'22:00')});
test('exposure uses current values and ignores invalid or negative values',()=>{assert.deepEqual(exposure([{currentValue:60},{currentValue:40},{currentValue:-3}]),{total:100,concentration:.6});assert.equal(exposure([]).concentration,0)});
test('alerts ignore old trades, non-trades, below-threshold size',()=>{assert.equal(newTrades([{type:'TRADE',timestamp:5,usdcSize:500},{type:'REDEEM',timestamp:6,usdcSize:900},{type:'TRADE',timestamp:6,usdcSize:10},{type:'TRADE',timestamp:6,usdcSize:501}],5,500).length,1)});
test('untrusted text escapes markup',()=>assert.equal(escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));

test('query rejects duplicated or unexpected keys across endpoint types',()=>{for(const q of ['kind=leaderboard&kind=activity','kind=leaderboard&timePeriod=DAY&timePeriod=DAY','kind=leaderboard&user='+wallet,'kind=activity&user='+wallet+'&limit=1000'])assert.throws(()=>upstream(new URLSearchParams(q)),/Invalid/) });
test('declared oversized bodies cancel before being read',async()=>{let cancelled=false;const response=new Response(new ReadableStream({cancel(){cancelled=true}}),{headers:{'content-length':'100'}});await assert.rejects(()=>readBounded(response,10),/exceeds/);assert.equal(cancelled,true)});
test('stream byte cap catches multibyte content without content-length and cancels',async()=>{let cancelled=false;const response=new Response(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('ééé'))},cancel(){cancelled=true}}));await assert.rejects(()=>readBounded(response,5),/exceeds/);assert.equal(cancelled,true)});
test('bounded stream decodes split unicode bytes',async()=>{const bytes=new TextEncoder().encode('é');const response=new Response(new ReadableStream({start(c){c.enqueue(bytes.slice(0,1));c.enqueue(bytes.slice(1));c.close()}}));assert.equal(await readBounded(response,2),'é')});
test('malformed upstream records are rejected per endpoint',()=>{for(const kind of ['leaderboard','positions','closed','activity'])for(const record of [null,{},[],42])assert.throws(()=>validateRows(kind,[record]),/format changed/);assert.throws(()=>validateRows('leaderboard',[{rank:1,proxyWallet:42,vol:1,pnl:1}]),/format changed/);assert.throws(()=>validateRows('positions',[{title:'x',outcome:'Yes',currentValue:null,cashPnl:1}]),/format changed/);assert.throws(()=>validateRows('closed',[{title:'x',outcome:'Yes',avgPrice:.5,realizedPnl:'NaN'}]),/format changed/)});
test('valid upstream metrics normalize numeric strings and discard extraneous keys',()=>{assert.deepEqual(validateRows('positions',[{title:'x',outcome:'Yes',currentValue:'5',cashPnl:-2,extra:'ignore'}]),[{title:'x',outcome:'Yes',currentValue:5,cashPnl:-2}])});
test('same-second distinct trades trigger once without replaying baseline',()=>{const a={type:'TRADE',timestamp:10,transactionHash:'a',usdcSize:500},b={...a,transactionHash:'b'};const initial=advanceActivity([a],undefined,100);assert.equal(initial.trades.length,0);const next=advanceActivity([a,b],initial.cursor,100);assert.deepEqual(next.trades,[b]);assert.equal(advanceActivity([a,b],next.cursor,100).trades.length,0)});
